const MIN_AGE = 0
const MAX_AGE = 100
const PASSWORD_MIN_LENGTH = 8
const NAME_MIN_LENGTH = 3
const LASTNAME_MIN_LENGTH = 3
const USERNAME_MIN_LENGTH = 5
const DNI_MIN_LENGTH = 7
const EMPTY_CHARACTER = ''
const SPACE = ' '

module.exports = {
  MIN_AGE,
  MAX_AGE,
  PASSWORD_MIN_LENGTH,
  NAME_MIN_LENGTH,
  LASTNAME_MIN_LENGTH,
  USERNAME_MIN_LENGTH,
  DNI_MIN_LENGTH,
  EMPTY_CHARACTER,
  SPACE,
}
